### ISSUE TITLE
research how to add JS visualization library for spectra and lightcurves

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/astrojsvis#1]
see aladinlite, how  it opens fits

need to to open astropy fits table, plot it with errorbars

https://www.astro.unige.ch/mmoda/gallery/data-products/1e-11451-6141-isgri-light-curve-61
https://www.astro.unige.ch/mmoda/gallery/data-products/1e-11451-6141-isgri-spectrum-59

this is done with bokeh (link missing)

other options are :
flot
plotly
d3

may reach into previous work of MM

**Comment by volodymyrss** [comment]
@burnout87  could you give a reference to the code about visualization with bokeh/python?

@motame could you put a reference to HEAVENS visualization library for the record?

**Comment by volodymyrss** [comment]
> Need to discuss metadata needed for the visualization (e.g. units from fits file header)

If you manage to open fits files from javascript library and access header, we can see how to do this.
Else we can use astropy to convert fits to json, there is a serializer already.

**Comment by burnout87** [comment]
> @burnout87 could you give a reference to the code about visualization with bokeh/python?

About bokeh, within the dispatcher, it is used mainly here:

https://github.com/oda-hub/dispatcher-app/blob/master/cdci_data_analysis/analysis/plot_tools.py

where the `Image`, `GridPlot` and `ScatterPlot` classes are implemented using bokeh (and js9), providing methods to create the dedicated html.

An example of usage of those classes is within the `oda_api`:

https://github.com/oda-hub/oda_api/blob/master/oda_api/plot_tools.py

Where for the gallery, bokeh is used for lightcurves and spectra products.

check the `get_html_image` method for those two classes

**Comment by francoismg** [comment]
@volodymyrss thanks for the write access, I have pushed the headers data from https://www.astro.unige.ch/mmoda/gallery/sites/default/files/IBIS_lc_1E_1145.1-6141_Eta_Carinae_7790003.0.fits in the "data_sample" folder
