### ISSUE TITLE
allow action to push to branch

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/astrojsvis#11]

**Comment by dsavchenko** [comment]
I wanted to use the `deploy-pr-preview` action and the required permission change is this https://github.com/marketplace/actions/deploy-pr-preview#grant-actions-permission-to-read-and-write-to-the-repository

**Comment by volodymyrss** [comment]
![image](https://github.com/esg-epfl-apc/astrojsvis/assets/3909535/78af985f-d144-42f5-9d20-833cb1d88fe2)


this repo has this set already seems?

**Comment by dsavchenko** [comment]
Great then!
