### ISSUE TITLE
Data table is shown as empty

### ISSUE THREAD

**Issue by dsavchenko** [esg-epfl-apc/astrojsvis#16]
Example with HESS spectrum on screenshot, but observed with other products as well

![image](https://github.com/esg-epfl-apc/astrojsvis/assets/56398430/19cecf04-4534-4b09-af81-7db56bcd862b)

**Comment by francoismg** [comment]
@dsavchenko does the primary header has data? or do you want the interface to be different when there's no data to present?

**Comment by dsavchenko** [comment]
> @dsavchenko does the primary header has data? or do you want the interface to be different when there's no data to present?

My fault, I didn't pay attention to which extension I'm viewing. Sorry for false alarm
