### ISSUE TITLE
make a gh page with both vis cases and fits reader

### ISSUE THREAD

**Issue by volodymyrss** [esg-epfl-apc/astrojsvis#7]

**Comment by francoismg** [comment]
As said on light curve vis issue, will move the changes to the main graph in a new file so it will look more like the final result

**Comment by volodymyrss** [comment]
Pages enabled as so:

![image](https://github.com/esg-epfl-apc/astrojsvis/assets/3909535/8f4b1868-a19f-4f17-83a4-dd7848ea0d63)

Please suggest change as needed. Maybe we should make it on main? Another dir?

**Comment by volodymyrss** [comment]
I changed to main.

**Comment by francoismg** [comment]
> Pages enabled as so:
> 
> Please suggest change as needed. Maybe we should make it on main? Another dir?
> 
> edit: **I changed to main, dir /docs**
> 
> it's showing in https://esg-epfl-apc.github.io/astrojsvis/ now. Please add there, @francoismg and @dsavchenko !

Thanks, think main is fine but another branch would have prevented people who want to fork it or something to have to download the gh pages with the actual project I think

**Comment by dsavchenko** [comment]
> Thanks, think main is fine but another branch would have prevented people who want to fork the actual project or something to have to download the gh pages with it I think

It's meant to be more a preview for us. No need to bother about forks, I think. 

As a side-note, it would be useful to use this action https://github.com/marketplace/actions/deploy-pr-preview at some point

**Comment by volodymyrss** [comment]
> > Thanks, think main is fine but another branch would have prevented people who want to fork the actual project or something to have to download the gh pages with it I think
> 
> It's meant to be more a preview for us. No need to bother about forks, I think.

Yes.

> As a side-note, it would be useful to use this action https://github.com/marketplace/actions/deploy-pr-preview at some point

Indeed, this would improve the flow. Actually, feel free to add it to your PR (and @francoismg please make a PR too), then we can see if we make it work (I will change the PR to gh-pages to check)

**Comment by dsavchenko** [comment]
I changed pages build to gh-pages branch.

To automatically add the PR preview, [configuration](https://github.com/marketplace/actions/deploy-pr-preview#grant-actions-permission-to-read-and-write-to-the-repository) required that I don't have permissions to do.

So I simulated manually what the preview action will do, just pushed to the gh-pages branch. 
Here is the link https://esg-epfl-apc.github.io/astrojsvis/manual-preview-pr/pr-5/lc_demo.html

@francoismg you can put a preview of the d3 viewer in the same way.

**Comment by volodymyrss** [comment]
> I changed pages build to gh-pages branch.
> 
> To automatically add the PR preview, [configuration](https://github.com/marketplace/actions/deploy-pr-preview#grant-actions-permission-to-read-and-write-to-the-repository) required that I don't have permissions to do.
> 
> So I simulated manually what the preview action will do, just pushed to the gh-pages branch. Here is the link https://esg-epfl-apc.github.io/astrojsvis/manual-preview-pr/pr-5/lc_demo.html
> 
> @francoismg you can put a preview of the d3 viewer in the same way.

Could you add a button to set LC url so we can try different ones easily?

**Comment by dsavchenko** [comment]
You mean the link to it in main index.html?

**Comment by francoismg** [comment]
> @francoismg you can put a preview of the d3 viewer in the same way.

Thanks, seems to be working.

I also added links to both demo in the main page
